service:
  type: ClusterIP
  targetPort: 3000

env:
  APP_ENV: staging

envSecrets:
  NPM_EMAIL: ofac-ti-ui-secrets
  NPM_AUTH: ofac-ti-ui-secrets

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80

probes:
  enabled: true
  path: /api/health/
  headers: {}
  liveness:
    httpGet: true
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi

ingress:
  enabled: true
  path: /academia
  hosts: ['ofac-ti-ui.devrel.staging.corp.mongodb.com']